[package]
name = "duplicheck-rs"
version = "0.1.0"
authors = ["petrSchreiber <petrschreiber@gmail.com>"]
edition = "2018"

[dependencies]
structopt = { version = "0.2", default-features = false }
md5 = "~0.6"
